### ISSUE TITLE
Necessity for Address and AddressRepresentation?

### ISSUE THREAD

**Issue by DieterDePaepe** [inspire-eu-rdf/inspire-rdf-guidelines#36]
A topic I had wondered about a bit already, and was briefly touched in [another discussion](https://github.com/inspire-eu-rdf/inspire-rdf-guidelines/issues/29#issuecomment-293879337):

Is there a need for both Address and AddressRepresentation in the RDF model? Can they not be merged?

By using only a (subclass of) `locn:Address`, that contains both the simply `locn` properties and the specialised INSPIRE attributes, users unfamiliar with INSPIRE would not be confused as to why the structured data of an address is stored in a different class.

**Comment by jechterhoff** [comment]
Good point. It looks like a pattern is emerging: A &lt;&lt;dataType&gt;&gt; of the INSPIRE conceptual schemas, which is primarily used as a facade for / simplified view on an INSPIRE &lt;&lt;featureType&gt;&gt;, could, in the RDF encoding, either be replaced by or merged with that feature type.

**Comment by jechterhoff** [comment]
In the revision of the [draft vocabularies](https://github.com/inspire-eu-rdf/inspire-rdf-vocabularies) and [guidelines](http://inspire-eu-rdf.github.io/inspire-rdf-guidelines/):
* Type 'AddressRepresentation' is mapped to the RDF implementation of type 'Address'.
* Type 'Address' is aligned with `locn:Address`.
* A [permission](http://inspire-eu-rdf.github.io/inspire-rdf-guidelines/#REC/OWL/type/mapping/dataTypeAsSpatialObjectTypeRepresentation) has been added to the guidelines, which states that _"a \<<dataType>> of the INSPIRE conceptual schemas, which is primarily used as a simplified view on an INSPIRE spatial object type, may, in the RDF encoding, either be mapped to or merged with that spatial object type."_ The following explanation was also added: _"When working with linked data, you should be able to directly link to a spatial object, rather than introducing an indirection by linking to a resource which merely provides a simplified view on the spatial object."_
